"""Add is_active to DriverProfile

Revision ID: 484cdb19e0ad
Revises: 
Create Date: 2026-02-26 16:29:37.482414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '484cdb19e0ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('driver_points_history', schema=None) as batch_op:
        batch_op.alter_column('sponsor_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('driver_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))
        batch_op.alter_column('streetname',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('zipcode',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_driver_profile_is_active'), ['is_active'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)

    with op.batch_alter_table('driver_profile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_driver_profile_is_active'))
        batch_op.alter_column('zipcode',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('streetname',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.drop_column('is_active')

    with op.batch_alter_table('driver_points_history', schema=None) as batch_op:
        batch_op.alter_column('sponsor_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
