"""Add invoice tables

Revision ID: 829939dc6f91
Revises: 484cdb19e0ad
Create Date: 2026-03-26 11:18:33.198114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '829939dc6f91'
down_revision = '484cdb19e0ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_driver_points_history')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_driver_points_history',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('link_id', sa.INTEGER(), nullable=False),
    sa.Column('points_change', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('current_points', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('update_date', sa.DATETIME(), nullable=False),
    sa.Column('reason', sa.VARCHAR(length=250), nullable=False),
    sa.Column('sponsor_user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['link_id'], ['driver_company_link.id'], ),
    sa.ForeignKeyConstraint(['sponsor_user_id'], ['sponsor_profile.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
